name: Test

on:
  push:
    branches:
      - main
    paths:
      - 'website/docs/**'
      - 'doc-detective/tests/**'

jobs:
  doc-detective:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Doc Detective
        run: npm install -g doc-detective

      - name: Run tests
        run: doc-detective --config doc-detective/config.json
